<?php

namespace App\Support\Observability\Alerts;

/**
 * Phase 0O.5A (ADR 0051 §14): the provider-neutral alert specification --
 * Prometheus-compatible alerting rules (the open format OpenMetrics
 * backends and the OpenTelemetry ecosystem's Prometheus-compatible stores
 * evaluate). No vendor-specific configuration is generated, and no
 * notification routing: the deployment attaches routing.
 *
 * Tiers whose operator value is unset are listed as DISABLED comments,
 * never silently omitted.
 */
final class AlertRulesExporter
{
    public const RUNBOOK_BASE = 'docs/operations/';

    public function yaml(): string
    {
        $lines = [
            '# Lycenza production alert rules -- GENERATED by `php artisan platform:alerts-export`',
            '# from App\\Support\\Observability\\Alerts\\AlertCatalog (ADR 0051 section 14). Do not edit by hand.',
            '# Provider-neutral Prometheus rule format; notification routing is a deployment decision.',
            'groups:',
            '  - name: lycenza-obs',
            '    rules:',
        ];

        foreach (AlertCatalog::all() as $rule) {
            if (! $rule->enabled()) {
                $lines[] = "      # {$rule->id} DISABLED: {$rule->disabledReason}";

                continue;
            }

            foreach ($rule->tiers as $tier) {
                $lines[] = '      - alert: '.$rule->alertName($tier['severity'], $tier['suffix']);
                $lines[] = '        expr: '.$this->quote($tier['expr']);
                if ($tier['for'] !== '0s') {
                    $lines[] = '        for: '.$tier['for'];
                }
                $lines[] = '        labels:';
                $lines[] = '          severity: '.$tier['severity']->label();
                $lines[] = '          sev: '.$tier['severity']->value;
                $lines[] = '          obs_id: '.$rule->id;
                $lines[] = '          threshold_source: '.$this->quote($rule->source);
                $lines[] = '        annotations:';
                $lines[] = '          summary: '.$this->quote($rule->summary);
                $lines[] = '          runbook: '.$this->quote(self::RUNBOOK_BASE.$rule->runbook);
            }
        }

        return implode("\n", $lines)."\n";
    }

    private function quote(string $value): string
    {
        return "'".str_replace("'", "''", $value)."'";
    }
}
