<?php

namespace App\Http\Controllers\App\HR;

use App\Domain\HR\Application\EmployeeImportService;
use App\Http\Controllers\Controller;
use App\Support\Authorization\AuthorizesCapability;
use App\Support\Tenancy\TenantContext;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Phase 8A closure correction (item 7 -- Employee Import activation) --
 * the UI activation of the already-built, already-tested
 * `EmployeeImportService` (8A.12). Deliberately accepts a raw JSON
 * array of rows (a `<textarea>`, not a CSV upload) -- building a CSV
 * parsing pipeline is a new engine this correction's mandate
 * explicitly forbids ("Do not build a second import engine"); JSON
 * pasted/generated by whatever spreadsheet tool an operator already
 * uses is the minimal activation of the EXISTING service's real
 * signature (`array<int, array<string, mixed>> $rows`), not a new one.
 */
class HrEmployeeImportController extends Controller
{
    use AuthorizesCapability;

    public function create(TenantContext $context): Response
    {
        $school = $context->requireSchool();
        $this->authorizeCapability('hr.employees.manage', $school);

        return Inertia::render('App/HR/Import/Create');
    }

    public function store(Request $request, TenantContext $context, EmployeeImportService $service): Response
    {
        $school = $context->requireSchool();
        $this->authorizeCapability('hr.employees.manage', $school);

        $validated = $request->validate([
            'rows_json' => ['required', 'string'],
        ]);

        $rows = json_decode($validated['rows_json'], true);

        if (! is_array($rows)) {
            throw ValidationException::withMessages(['rows_json' => ['This must be a valid JSON array of row objects.']]);
        }

        $result = $service->import($school, $context->actor(), $rows);

        return Inertia::render('App/HR/Import/Result', [
            'result' => $result->toArray(),
        ]);
    }
}
