<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Central/platform data -- see the migration's docblock and
 * docs/architecture/adr/0025-transactional-outbox.md. `id` IS the
 * event id (UUIDv7, generated by App\Support\Events\EventEnvelope
 * before this row is created, not by GeneratesUuidV7's `creating`
 * hook) -- this model does NOT use that trait.
 *
 * @property string $id
 * @property string $event_type
 * @property int $event_version
 * @property string|null $school_id
 * @property string|null $campus_id
 * @property string|null $actor_id
 * @property string|null $request_id
 * @property string $correlation_id
 * @property string|null $causation_id
 * @property array $payload
 * @property array $metadata
 * @property Carbon $occurred_at
 * @property Carbon $available_at
 * @property string $status
 * @property int $attempts
 * @property string|null $last_error
 * @property Carbon|null $dispatched_at
 */
class DomainEventOutbox extends Model
{
    protected $table = 'domain_event_outbox';

    public $incrementing = false;

    protected $keyType = 'string';

    protected $guarded = [];

    protected function casts(): array
    {
        return [
            'payload' => 'array',
            'metadata' => 'array',
            'occurred_at' => 'datetime',
            'available_at' => 'datetime',
            'dispatched_at' => 'datetime',
        ];
    }
}
