<?php

namespace App\Console\Commands;

use App\Models\ServiceIdentity;
use App\Support\ServiceIdentities\ServiceIdentityIssuer;
use Illuminate\Console\Command;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Support\Facades\DB;

/**
 * Phase 0O.1: the operator path for issuing a NEW service identity (e.g.
 * the AI Gateway's credential in a real deployment, where
 * ServiceIdentitySeeder refuses to run). Console only -- no HTTP, no UI.
 *
 * The credential is generated by ServiceIdentityIssuer, stored only as a
 * sha256 hash, audited without it (`platform.service_identity.issued`:
 * slug and capabilities), never logged, and printed to this terminal
 * exactly once. An existing slug is refused: there is no rotation or
 * expiry yet (Phase 0O decision O5) -- disable the identity and issue a
 * new one instead.
 */
class IssueServiceIdentity extends Command
{
    protected $signature = 'platform:service-identity-issue
        {slug : A new, unique identity slug (lowercase letters, digits and hyphens)}
        {--name= : A display name (defaults to the slug)}
        {--capability=* : A capability to grant (ai.tools.invoke, ai.audit.write); repeatable}
        {--force : Skip the interactive confirmation (trusted operator automation only)}';

    protected $description = 'Issue a new service identity and print its credential once (operator console only).';

    public function handle(ServiceIdentityIssuer $issuer): int
    {
        $slug = (string) $this->argument('slug');
        /** @var list<string> $capabilities */
        $capabilities = array_values(array_unique(array_map('strval', (array) $this->option('capability'))));
        $name = trim((string) ($this->option('name') ?? '')) ?: $slug;

        if (preg_match('/^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$/', $slug) !== 1) {
            $this->error('Refused: the slug must be 3-64 lowercase letters, digits or hyphens.');

            return self::FAILURE;
        }

        if ($capabilities === [] || array_diff($capabilities, ServiceIdentityIssuer::ISSUABLE_CAPABILITIES) !== []) {
            $this->error('Refused: pass at least one --capability, each one of: '.implode(', ', ServiceIdentityIssuer::ISSUABLE_CAPABILITIES).'.');

            return self::FAILURE;
        }

        if (ServiceIdentity::query()->where('slug', $slug)->exists()) {
            $this->error('Refused: a service identity with that slug already exists. Rotation is not available; disable it and issue a new identity.');

            return self::FAILURE;
        }

        if (strlen($name) > 255) {
            $this->error('Refused: the name is too long.');

            return self::FAILURE;
        }

        if (! $this->confirmed("Issue service identity [{$slug}] with: ".implode(', ', $capabilities).'?')) {
            return self::FAILURE;
        }

        try {
            // One transaction: the identity, its capabilities and its audit
            // event exist together or not at all.
            $credential = DB::transaction(fn (): string => $issuer->issue($slug, $name, $capabilities)[1]);
        } catch (UniqueConstraintViolationException) {
            $this->error('Refused: a service identity with that slug already exists. Rotation is not available; disable it and issue a new identity.');

            return self::FAILURE;
        }

        $this->warn('Service credential -- shown ONCE, never stored or shown again. Copy it into the calling service\'s secret configuration now:');
        $this->line($credential);

        return self::SUCCESS;
    }

    private function confirmed(string $question): bool
    {
        if ($this->option('force')) {
            return true;
        }

        if (! $this->input->isInteractive()) {
            $this->error('Refused: confirmation is required. Run interactively, or pass --force from trusted operator automation.');

            return false;
        }

        if (! $this->confirm($question)) {
            $this->info('Nothing changed.');

            return false;
        }

        return true;
    }
}
